/* Indagine customer satisfaction utenti edilizia privata comune di Padova   */
/* Prova pratica finale corso Statistica Sociale                             */
/*                                                                           */
/*                                                                           */
/* Dati in Utenza01.txt                                                      */
/* editor HandyHtml replace \t\t con \t.\t piu' volte su utenza01.txt        */
/*                  replace \t con ^  e salva su Utenza02.txt                */


libname dati "/home/clto9100" ;
run;

DATA dati.utenza;
INFILE '/home/clto9100/Utenza02.txt'
        FIRSTOBS=2 LRECL=600 MISSOVER DELIMITER='^' ;   /* OBS=11 ;          */
INPUT x1-x3 x4$ x5-x9 x10$ x11 x12 x13$ x14 x15$ x16 x17$ x18 x19$ x20 x21$
      x22-x59 x60$ x61$ x62 x63 x64$ x65$ x66 x67 x68$ x69$ x70-x75 ;
RUN;

DATA dati.utenza03;           /* dataset senza campi stringa               */
SET dati.utenza;            /* carica set precedente                     */
DROP x4 x10 x13 x15 x17 x19 x21 x60 x61 x64 x65 x68 x69; /* non mettere $    */
RUN;

/* PROC PRINT;    */
/* RUN;           */
/* PROC FSVIEW;   */
/* RUN;
/* PROC CONTENTS;                                 */
/* RUN;                                           */
/* PROC FREQ;                                     */
/* RUN;                                           */
/* PROC CORR;                                     */
/* RUN;                                           */
/* PROC GPLOT;                                    */
/* PLOT x6 * x24 / FRAME ; RUN; QUIT;             */
/* PROC LOGISTIC DATA=statso.utenza02 ;  */
/* MODEL x24 = x5 x6 x7 ; RUN;   */

PROC GCHART ;
AXIS1 LABEL=(ANGLE=90 JUSTIFY=CENTER 'Frequenze assolute');
AXIS2 LABEL=('Asse x');

VBAR  x2  / MIDPOINTS =  1 2  FRAME  TYPE=FREQ FREQ MAXIS=AXIS2 RAXIS=AXIS1;

RUN; QUIT;

PROC GCHART ;
VBAR  x3  / MIDPOINTS = 1 2 3 4 5 6 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
/*                               */
/*PROC GCHART ;
VBAR  x5  / MIDPOINTS = 1 2 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x6  / MIDPOINTS = 1 2 3 4 5 6 7 8 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x7  / MIDPOINTS = 1 2 3 4 5 6 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x8  / MIDPOINTS = 1 2 3 4 5 6 7 8 9 99 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x9  / MIDPOINTS = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x11  / MIDPOINTS = 1 2 3 4 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x12  / MIDPOINTS = 1 2 3 4 5 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x14  / MIDPOINTS = 1 2 3 4 5 6 7 8 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x16  / MIDPOINTS = 1 2 3 4 5 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x18  / MIDPOINTS = 1 2 3 5 6 7 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x20  / MIDPOINTS = 1 2 3 4 5 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x22  / MIDPOINTS = 1 2 3 4 5 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x23  / MIDPOINTS = 1 2 3 4 5 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x24  / MIDPOINTS = 1 2 3 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x25  / MIDPOINTS = 1 2 3 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x26  / MIDPOINTS = 1 2 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x27  / MIDPOINTS = 1 2 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x28  / MIDPOINTS = 1 2 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x29  / MIDPOINTS = 1 2 3 4 5 6 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x30  / MIDPOINTS = 1 2 3 4 5 6 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x31  / MIDPOINTS = 1 2 3 4 5 6 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x32  / MIDPOINTS = 1 2 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x33  / MIDPOINTS = 1 2 3 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x34  / MIDPOINTS = 1 2 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x35  / MIDPOINTS = 1 2 3 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x36  / MIDPOINTS = 1 2 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x37  / MIDPOINTS = 1 2 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x38  / MIDPOINTS = 1 2 3 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x39  / MIDPOINTS = 1 2 3 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x40  / MIDPOINTS = 1 2 3 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x41  / MIDPOINTS = 1 2 3 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x42  / MIDPOINTS = 1 2 3 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x43  / MIDPOINTS = 1 2 3 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x44  / MIDPOINTS = 1 2 3 4 5 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x45  / MIDPOINTS = 1 2 3 4 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x46  / MIDPOINTS = 1 2 3 4 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x47  / MIDPOINTS = 1 2 3 4 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x48  / MIDPOINTS = 1 2 3 4 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x49  / MIDPOINTS = 1 2 3 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x50  / MIDPOINTS = 1 2 3 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x51  / MIDPOINTS = 1 2 3 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x52  / MIDPOINTS = 1 2 3 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x53  / MIDPOINTS = 1 2 3 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x54  / MIDPOINTS = 1 2 3 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x55  / MIDPOINTS = 1 2 3 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x56  / MIDPOINTS = 1 2 3 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x57  / MIDPOINTS = 1 2 3 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x58  / MIDPOINTS = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 99 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x59  / MIDPOINTS = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 99 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x62  / MIDPOINTS = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 99 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x63  / MIDPOINTS = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 99 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x66  / MIDPOINTS = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 99 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x67  / MIDPOINTS = 1 2 3 4 5 6 7 8 9 10 11 12 13 14 99 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x70  / MIDPOINTS = 1 2 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x71  / MIDPOINTS = 1 2 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x72  / MIDPOINTS = 1 2 9 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x73  / MIDPOINTS = 1 2 9FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x74  / MIDPOINTS = 1 2 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;
PROC GCHART ;
VBAR  x75  / MIDPOINTS = 1 2 FRAME  TYPE=FREQ FREQ ;
RUN; QUIT;                                                 */
